### PR TITLE
Drippets

### PR DESCRIPTION
**Pull request by richardbporter**
Starting a PR for discussion and issue tracking.

### CODE REVIEW

**Comment by richardbporter** [comment]
@ITS-UofIowa/web-team Brandon made a good point about managing these. Right now, you'd have to `git pull` to get the latest code. We may want to investigate creating a package so updates are handled automatically.

**Comment by brandonneil** [comment]
Submitting a package to package control won't be bad: https://packagecontrol.io/docs/submitting_a_package

I'll plan to work on that once this PR is merged.

**Comment by richardbporter** [comment]
I' not sure how https://github.com/ITS-UofIowa/drupal_code_snippets/blob/master/feeds/run_feed_import.php is being used but Feeds now has Drush integration to run feeds.

`drush help --filter=feeds`

**Comment by joewhitsitt** [comment]
@richardbporter we used the feeds import as part of a huge collection of updates. The feed was new and we wanted to run the initial import so we could then do stuff with the newly imported content. drush is nice, but would have probably run out of order in this situation.

**Pull request merged**
